services:
  - type: web
    name: fresco-learning
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///data/fresco.db
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /data/uploads
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
